// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9OeOkTPhN5DMgNL0WYd3SGPd50hSE7o',
    appId: '1:48923210947:web:65c0eab7df4cfd75c05e76',
    messagingSenderId: '48923210947',
    projectId: 'mentor-00571',
    authDomain: 'mentor-00571.firebaseapp.com',
    storageBucket: 'mentor-00571.appspot.com',
    measurementId: 'G-5E3LZG7VT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsfrgXV_0okWnXL2C350eAH3uKg0I8GFo',
    appId: '1:48923210947:android:e5f3212117b15c44c05e76',
    messagingSenderId: '48923210947',
    projectId: 'mentor-00571',
    storageBucket: 'mentor-00571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNz_QiE8DJeFPsrCYB9KOjhP6TAGsAvUM',
    appId: '1:48923210947:ios:5b2d3d063475dca1c05e76',
    messagingSenderId: '48923210947',
    projectId: 'mentor-00571',
    storageBucket: 'mentor-00571.appspot.com',
    iosClientId: '48923210947-nilpb3ath0jedj6db3rp2m7ge00a6pa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentor',
  );
}
